language: ruby
rvm:
  - 2.1.0
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y software-properties-common
  - sudo apt-get install -y build-essential libfontconfig
  - nvm install 0.10.32
  - nvm use 0.10.32
  - npm update npm -g
install:
  - npm install --global quickscrape@0.3.2
script:
  - ruby test/test_all.rb
