language: ruby
rvm:
  - 2.5.1
before_install:
  - nvm install 8.11.3
  - nvm use 8.11.3
  - npm update npm -g
install:
  - npm install --global quickscrape@0.4.6
script:
  - ruby test/test_all.rb
sudo: false
